# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cmatei/qt-tests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cmatei/qt-tests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmatei/qt-tests/CMakeFiles /home/cmatei/qt-tests//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmatei/qt-tests/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testsim

# Build rule for target.
testsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testsim
.PHONY : testsim

# fast build rule for target.
testsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/build
.PHONY : testsim/fast

audioprocess.o: audioprocess.cpp.o
.PHONY : audioprocess.o

# target to build an object file
audioprocess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/audioprocess.cpp.o
.PHONY : audioprocess.cpp.o

audioprocess.i: audioprocess.cpp.i
.PHONY : audioprocess.i

# target to preprocess a source file
audioprocess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/audioprocess.cpp.i
.PHONY : audioprocess.cpp.i

audioprocess.s: audioprocess.cpp.s
.PHONY : audioprocess.s

# target to generate assembly for a file
audioprocess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/audioprocess.cpp.s
.PHONY : audioprocess.cpp.s

calllist.o: calllist.cpp.o
.PHONY : calllist.o

# target to build an object file
calllist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/calllist.cpp.o
.PHONY : calllist.cpp.o

calllist.i: calllist.cpp.i
.PHONY : calllist.i

# target to preprocess a source file
calllist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/calllist.cpp.i
.PHONY : calllist.cpp.i

calllist.s: calllist.cpp.s
.PHONY : calllist.s

# target to generate assembly for a file
calllist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/calllist.cpp.s
.PHONY : calllist.cpp.s

contest.o: contest.cpp.o
.PHONY : contest.o

# target to build an object file
contest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/contest.cpp.o
.PHONY : contest.cpp.o

contest.i: contest.cpp.i
.PHONY : contest.i

# target to preprocess a source file
contest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/contest.cpp.i
.PHONY : contest.cpp.i

contest.s: contest.cpp.s
.PHONY : contest.s

# target to generate assembly for a file
contest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/contest.cpp.s
.PHONY : contest.cpp.s

dxoper.o: dxoper.cpp.o
.PHONY : dxoper.o

# target to build an object file
dxoper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/dxoper.cpp.o
.PHONY : dxoper.cpp.o

dxoper.i: dxoper.cpp.i
.PHONY : dxoper.i

# target to preprocess a source file
dxoper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/dxoper.cpp.i
.PHONY : dxoper.cpp.i

dxoper.s: dxoper.cpp.s
.PHONY : dxoper.s

# target to generate assembly for a file
dxoper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/dxoper.cpp.s
.PHONY : dxoper.cpp.s

dxstation.o: dxstation.cpp.o
.PHONY : dxstation.o

# target to build an object file
dxstation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/dxstation.cpp.o
.PHONY : dxstation.cpp.o

dxstation.i: dxstation.cpp.i
.PHONY : dxstation.i

# target to preprocess a source file
dxstation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/dxstation.cpp.i
.PHONY : dxstation.cpp.i

dxstation.s: dxstation.cpp.s
.PHONY : dxstation.s

# target to generate assembly for a file
dxstation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/dxstation.cpp.s
.PHONY : dxstation.cpp.s

keyer.o: keyer.cpp.o
.PHONY : keyer.o

# target to build an object file
keyer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/keyer.cpp.o
.PHONY : keyer.cpp.o

keyer.i: keyer.cpp.i
.PHONY : keyer.i

# target to preprocess a source file
keyer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/keyer.cpp.i
.PHONY : keyer.cpp.i

keyer.s: keyer.cpp.s
.PHONY : keyer.s

# target to generate assembly for a file
keyer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/keyer.cpp.s
.PHONY : keyer.cpp.s

mystation.o: mystation.cpp.o
.PHONY : mystation.o

# target to build an object file
mystation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/mystation.cpp.o
.PHONY : mystation.cpp.o

mystation.i: mystation.cpp.i
.PHONY : mystation.i

# target to preprocess a source file
mystation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/mystation.cpp.i
.PHONY : mystation.cpp.i

mystation.s: mystation.cpp.s
.PHONY : mystation.s

# target to generate assembly for a file
mystation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/mystation.cpp.s
.PHONY : mystation.cpp.s

qrmstation.o: qrmstation.cpp.o
.PHONY : qrmstation.o

# target to build an object file
qrmstation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qrmstation.cpp.o
.PHONY : qrmstation.cpp.o

qrmstation.i: qrmstation.cpp.i
.PHONY : qrmstation.i

# target to preprocess a source file
qrmstation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qrmstation.cpp.i
.PHONY : qrmstation.cpp.i

qrmstation.s: qrmstation.cpp.s
.PHONY : qrmstation.s

# target to generate assembly for a file
qrmstation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qrmstation.cpp.s
.PHONY : qrmstation.cpp.s

qrnstation.o: qrnstation.cpp.o
.PHONY : qrnstation.o

# target to build an object file
qrnstation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qrnstation.cpp.o
.PHONY : qrnstation.cpp.o

qrnstation.i: qrnstation.cpp.i
.PHONY : qrnstation.i

# target to preprocess a source file
qrnstation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qrnstation.cpp.i
.PHONY : qrnstation.cpp.i

qrnstation.s: qrnstation.cpp.s
.PHONY : qrnstation.s

# target to generate assembly for a file
qrnstation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qrnstation.cpp.s
.PHONY : qrnstation.cpp.s

qsb.o: qsb.cpp.o
.PHONY : qsb.o

# target to build an object file
qsb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qsb.cpp.o
.PHONY : qsb.cpp.o

qsb.i: qsb.cpp.i
.PHONY : qsb.i

# target to preprocess a source file
qsb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qsb.cpp.i
.PHONY : qsb.cpp.i

qsb.s: qsb.cpp.s
.PHONY : qsb.s

# target to generate assembly for a file
qsb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/qsb.cpp.s
.PHONY : qsb.cpp.s

random.o: random.cpp.o
.PHONY : random.o

# target to build an object file
random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i
.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s
.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/random.cpp.s
.PHONY : random.cpp.s

station.o: station.cpp.o
.PHONY : station.o

# target to build an object file
station.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/station.cpp.o
.PHONY : station.cpp.o

station.i: station.cpp.i
.PHONY : station.i

# target to preprocess a source file
station.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/station.cpp.i
.PHONY : station.cpp.i

station.s: station.cpp.s
.PHONY : station.s

# target to generate assembly for a file
station.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/station.cpp.s
.PHONY : station.cpp.s

testsim_daemon.o: testsim_daemon.cpp.o
.PHONY : testsim_daemon.o

# target to build an object file
testsim_daemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/testsim_daemon.cpp.o
.PHONY : testsim_daemon.cpp.o

testsim_daemon.i: testsim_daemon.cpp.i
.PHONY : testsim_daemon.i

# target to preprocess a source file
testsim_daemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/testsim_daemon.cpp.i
.PHONY : testsim_daemon.cpp.i

testsim_daemon.s: testsim_daemon.cpp.s
.PHONY : testsim_daemon.s

# target to generate assembly for a file
testsim_daemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/testsim_daemon.cpp.s
.PHONY : testsim_daemon.cpp.s

winkeyer.o: winkeyer.cpp.o
.PHONY : winkeyer.o

# target to build an object file
winkeyer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/winkeyer.cpp.o
.PHONY : winkeyer.cpp.o

winkeyer.i: winkeyer.cpp.i
.PHONY : winkeyer.i

# target to preprocess a source file
winkeyer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/winkeyer.cpp.i
.PHONY : winkeyer.cpp.i

winkeyer.s: winkeyer.cpp.s
.PHONY : winkeyer.s

# target to generate assembly for a file
winkeyer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsim.dir/build.make CMakeFiles/testsim.dir/winkeyer.cpp.s
.PHONY : winkeyer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testsim"
	@echo "... audioprocess.o"
	@echo "... audioprocess.i"
	@echo "... audioprocess.s"
	@echo "... calllist.o"
	@echo "... calllist.i"
	@echo "... calllist.s"
	@echo "... contest.o"
	@echo "... contest.i"
	@echo "... contest.s"
	@echo "... dxoper.o"
	@echo "... dxoper.i"
	@echo "... dxoper.s"
	@echo "... dxstation.o"
	@echo "... dxstation.i"
	@echo "... dxstation.s"
	@echo "... keyer.o"
	@echo "... keyer.i"
	@echo "... keyer.s"
	@echo "... mystation.o"
	@echo "... mystation.i"
	@echo "... mystation.s"
	@echo "... qrmstation.o"
	@echo "... qrmstation.i"
	@echo "... qrmstation.s"
	@echo "... qrnstation.o"
	@echo "... qrnstation.i"
	@echo "... qrnstation.s"
	@echo "... qsb.o"
	@echo "... qsb.i"
	@echo "... qsb.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... station.o"
	@echo "... station.i"
	@echo "... station.s"
	@echo "... testsim_daemon.o"
	@echo "... testsim_daemon.i"
	@echo "... testsim_daemon.s"
	@echo "... winkeyer.o"
	@echo "... winkeyer.i"
	@echo "... winkeyer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

